version: '3'

services:
  backend:
    container_name: dvb-backend
    restart: always
    build:
      context: ./backend
    command: >
      bash -c "python manage.py migrate
      && python manage.py create_superuser
      && python manage.py add_sampledata
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - default

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: dvb-db
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "13307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: djangovuedb
      MYSQL_USER: admin1
      MYSQL_PASSWORD: admin1
      TZ: "Asia/Tokyo"
    networks:
      - default

  
networks:
  default:
    driver: bridge
 